# Generated by Django 6.0.7 on 2026-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='notes',
            new_name='doctor_notes',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='report_file',
            new_name='medical_report',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
    ]
