# Generated by Django 6.0.7 on 2026-07-25 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='advice',
            new_name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(help_text='Medicine list with dosage'),
        ),
    ]
