# Generated by Django 6.0.7 on 2026-07-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('General Medicine', 'General Medicine'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry')], max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField(help_text='Experience in Years')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('available', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
